### ISSUE TITLE
Please use Save-Actions / Auto-Formatter

### ISSUE THREAD

**Issue by DrGlitchMX** [FloLei/KeycloakDatabaseConnector#1]
https://github.com/FloLei/KeycloakDatabaseConnector/blob/63915b7562475fe28608cf8da31c2dabb5cb4c72/KeycloakDatabaseConnector/src/main/java/com/msg/storage/provider/MsgKeycloakUserStorageProvider.java#L54

Just a suggestion: Activate Eclipse Save-Actions and "Format Code on Save"

**Comment by FloLei** [comment]
Forgot to activate the option -> Done
