### ISSUE TITLE
Unboxing not necessary , "Integer.valueOf" already delivers int

### ISSUE THREAD

**Issue by DrGlitchMX** [FloLei/KeycloakDatabaseConnector#4]
https://github.com/FloLei/KeycloakDatabaseConnector/blob/63915b7562475fe28608cf8da31c2dabb5cb4c72/KeycloakDatabaseConnector/src/main/java/com/msg/storage/adapter/UserAdapter.java#L150

**Comment by FloLei** [comment]
Integer.valueOf returns an Integer Object, but unboxing here is unnecessary like you said, because setId expects an primitive int value so the unboxing is done by the the Java compiler -> done
