### ISSUE TITLE
Duplicate code, see method "searchForUsers"

### ISSUE THREAD

**Issue by DrGlitchMX** [FloLei/KeycloakDatabaseConnector#7]
https://github.com/FloLei/KeycloakDatabaseConnector/blob/63915b7562475fe28608cf8da31c2dabb5cb4c72/KeycloakDatabaseConnector/src/main/java/com/msg/storage/provider/MsgKeycloakUserStorageProvider.java#L246

**Comment by FloLei** [comment]
done
