### ISSUE TITLE
Method is a bit long and can be broken down into 3

### ISSUE THREAD

**Issue by DrGlitchMX** [FloLei/KeycloakDatabaseConnector#8]
https://github.com/FloLei/KeycloakDatabaseConnector/blob/63915b7562475fe28608cf8da31c2dabb5cb4c72/KeycloakDatabaseConnector/src/main/java/com/msg/storage/provider/MsgKeycloakUserStorageProvider.java#L314

**Comment by FloLei** [comment]
Done
